name: Hydroponix
description: "Hydroponix"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_ui_auth: ^1.12.1
  firebase_ui_oauth_google: ^1.2.17
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  http: ^1.2.1
  permission_handler: ^11.3.0
  wifi_iot: ^0.3.19
  wifi_scan: ^0.4.1
  uuid: ^4.3.3
  cloud_firestore: ^5.4.0
  connectivity_plus: ^4.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  mqtt_client: ^10.2.1
  fl_chart: ^0.69.0
  skeletonizer: ^1.4.2
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1
  shopify_flutter: ^2.1.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - .env
