// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgZdCuSXl32Vki_hSbBYPpaM8YkofjEE',
    appId: '1:643683883154:web:9a9b537aeefb65e5f6ae4b',
    messagingSenderId: '643683883154',
    projectId: 'hydroponix-29d2d',
    authDomain: 'hydroponix-29d2d.firebaseapp.com',
    storageBucket: 'hydroponix-29d2d.appspot.com',
    measurementId: 'G-YC9X0TBGJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvUvv2_FVipMmfDxftjK9zsdszOq2Wuio',
    appId: '1:643683883154:android:e3371da667a522ebf6ae4b',
    messagingSenderId: '643683883154',
    projectId: 'hydroponix-29d2d',
    storageBucket: 'hydroponix-29d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuq06v4i5cSRIAvWWw5PTckeBkKFvz5-A',
    appId: '1:643683883154:ios:d5d23ed947373a2ef6ae4b',
    messagingSenderId: '643683883154',
    projectId: 'hydroponix-29d2d',
    storageBucket: 'hydroponix-29d2d.appspot.com',
    androidClientId: '643683883154-hnl070dqqg11pnmb9ad4cqkq6psqi2q7.apps.googleusercontent.com',
    iosClientId: '643683883154-sdllclhgnqhtkch4kus2stjg551a5pdv.apps.googleusercontent.com',
    iosBundleId: 'com.hydroponix.hydroponix',
  );
}
